In [2]:
import numpy as np

Basic Array Creations

In [3]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
l = [1,2,3.5,'supp']
print(l)
larr = np.array(l)
print(larr)

[1, 2, 3.5, 'supp']
['1' '2' '3.5' 'supp']


Only same data type is stored in a numpy array ,
As u can see in the above example , An array with multiple data types was converted into a string.
An array containing integers and floating point numbers will be converted into an array of floating point numbers.

Below is an example of a 2D array , array with dimensions above 2 are tensors.

In [ ]:
normalList = [[1,2,3],[4,5,6],[7,8,9]]
print(normalList,"\n")
matrix = np.array(normalList)
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Generation Function

In [13]:
Zero1 = np.zeros(5)
Zero2 = np.zeros((3,4))

Ones1 = np.ones(3)
Ones2 = np.ones((3,5))

print(Zero1)
print(Zero2)

LinearSpacing = np.linspace(1,10,5)
print(LinearSpacing)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1.    3.25  5.5   7.75 10.  ]


Random Generation Function


In [ ]:
arr = np.random.rand(10) #Between -1 and 1 , Normalization
print(arr)

arr1 = np.random.randn(10) #Between -3 and 3 , i.e. , Standardization
print(arr1)

arr2 = np.random.randint(10,30,5) #Hover over it to know more about it  
print(arr2)

[0.26793925 0.31880998 0.7961065  0.5932481  0.95616589 0.014594
 0.87083757 0.91659413 0.03208093 0.89337969]
[ 0.86185741  0.72928925  1.22043197  0.42028801  0.3456602  -0.33943205
 -0.47610704  0.43326144 -2.71553465  0.12551859]
7


Array attributes