In [2]:
import numpy as np 

# NUMPY INDEXING AND SLICING OF VECTORS <br>
Same as lists in python

In [4]:
arr = np.arange(10,21)
print(arr)

#SLICING
arr_slice = arr[3::2]
print(arr_slice)


[10 11 12 13 14 15 16 17 18 19 20]
[13 15 17 19]


# INDEXING AND SLICING OF MATRIX

In [ ]:
matrix = np.arange(1,31).reshape(6,5)

print(matrix,"\n")

print(matrix[1],"\n") #Prints the row

print(matrix[2][3],"\n") #Prints the number at that index

print(matrix[1:3,2:4],"\n") #Slicing

print(matrix[:,3]) #Output is a vector


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[ 6  7  8  9 10] 

14 

[[ 8  9]
 [13 14]] 

[ 4  9 14 19 24 29]


# BOOLEAN INDEXING

In [ ]:
arr =  np.arange(11,21)
print(arr)

bool_index = arr % 2 == 0 #Condition stating elements of the array are even
print(bool_index)

arr = arr[bool_index] #Index with True value are accepted
print(arr)

[11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True]
[12 14 16 18 20]
