# ARRAY OPERATIONS

Arithmetic Operations

In [1]:
import numpy as np

In [2]:
arr1 =  np.array([0,1,2,3,4])
arr2 =  np.array([5,6,7,8,9])

In [3]:
arr1+arr2

array([ 5,  7,  9, 11, 13])

In [4]:
arr1*arr2

array([ 0,  6, 14, 24, 36])

In [5]:
arr1**arr2

array([     0,      1,    128,   6561, 262144])

In [ ]:
arr1//arr2

In [ ]:
arr1/arr2

Broadcasting

In [7]:
arr1 + 10

array([10, 11, 12, 13, 14])

In [ ]:
arr3 = np.arange(1,26).reshape(5,5)

arr3 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow Copy

In [ ]:
slice = arr3[1]

slice = slice + 50
print(slice)

print(arr3) # NOTICE : The values in the arr3 from which slice was taken doesnt change , this is the concept of Shallow Copy . ONLY the sliced array is assigned a new location in the RAM , if the whole array is passed on , like this , arr4 = arr3 , then both are reffering to the same array.This is DEEP COPY.

#To pass on an array without referring to the same array , do this

arr4 = arr3.copy()


[56 57 58 59 60]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


MATRIX MULTIPLICATION

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

A @ B

array([[16, 19],
       [36, 43]])

In [18]:
np.dot(A,B)

array([[16, 19],
       [36, 43]])

Transpose

In [19]:
A.T

array([[1, 3],
       [2, 4]])

Advanced Array Manipulation

Stacking Array

In [ ]:
a =  np.array([0,1,2,3,4])
b =  np.array([5,6,7,8,9])

#In stacking , you are supposed to use only vectors/arrays not matrices

In [24]:
np.vstack((a,b))



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.column_stack((a,b))

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Splitting Array

In [ ]:
A = np.arange(1,26).reshape(5,5)

In [35]:
np.hsplit(A,5)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]])]

In [32]:
np.vsplit(A,5)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25]])]